=== CarlosMartinez-USDA/NAL-MARCXML2MODS3-7/commons/xml/marcCountry.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://www.local.gov/marc/countries" xmlns:marccountry="http://www.local.gov/marc/countries">
  <xs:element name="marcCountry">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="marccountry:value"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="value">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="marccountry:code"/>
        <xs:element ref="marccountry:country"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="code" type="xs:NMTOKEN"/>
  <xs:element name="country" type="xs:string"/>
</xs:schema>

=== CarlosMartinez-USDA/NAL-MARCXML2MODS3-7/commons/xml/marcCountry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--THIS FILE IS USED TO CONVERT MARC COUNTRY CODES INTO THEIR RESPECTIVE COUNTRY NAMES-->  							
<marcCountry  xmlns="http://www.local.gov/marc/countries" 
    xmlns:marccountry="http://www.local.gov/marc/countries"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.local.gov/marc/countries marcCountry.xsd">
    <value>
       <code>aa</code>
        <country>Albania</country>
    </value>
    <value>
       <code>abc</code>
        <country>Alberta</country>
    </value>
    <value>
       <code>-ac</code>
        <country>Ashmore and Cartier Islands</country>
    </value>
    <value>
       <code>aca</code>
        <country>Australian Capital Territory</country>
    </value>
    <value>
       <code>ae</code>
        <country>Algeria</country>
    </value>
    <value>
       <code>af</code>
        <country>Afghanistan</country>
    </value>
    <value>
       <code>ag</code>
        <country>Argentina</country>
    </value>
    <value>
       <code>-ai</code>
        <country>Anguilla</country>
    </value>
    <value>
       <code>ai</code>
        <country>Armenia (Republic)</country>
    </value>
    <value>
       <code>-air</code>
        <country>Armenian S.S.R.</country>
    </value>
    <value>
       <code>aj</code>
        <country>Azerbaijan</country>
    </value>
    <value>
       <code>-ajr</code>
        <country>Azerbaijan S.S.R.</country>
    </value>
    <value>
       <code>aku</code>
        <country>Alaska</country>
    </value>
    <value>
       <code>alu</code>
        <country>Alabama</country>
    </value>
    <value>
       <code>am</code>
        <country>Anguilla</country>
    </value>
    <value>
       <code>an</code>
        <country>Andorra</country>
    </value>
    <value>
       <code>ao</code>
        <country>Angola</country>
    </value>
    <value>
       <code>aq</code>
        <country>Antigua and Barbuda</country>
    </value>
    <value>
       <code>aru</code>
        <country>Arkansas</country>
    </value>
    <value>
       <code>as</code>
        <country>American Samoa</country>
    </value>
    <value>
       <code>at</code>
        <country>Australia</country>
    </value>
    <value>
       <code>au</code>
        <country>Austria</country>
    </value>
    <value>
       <code>aw</code>
        <country>Aruba</country>
    </value>
    <value>
       <code>ay</code>
        <country>Antarctica</country>
    </value>
    <value>
       <code>azu</code>
        <country>Arizona</country>
    </value>
    <value>
       <code>ba</code>
        <country>Bahrain</country>
    </value>
    <value>
       <code>bb</code>
        <country>Barbados</country>
    </value>
    <value>
       <code>bcc</code>
        <country>British Columbia</country>
    </value>
    <value>
       <code>bd</code>
        <country>Burundi</country>
    </value>
    <value>
       <code>be</code>
        <country>Belgium</country>
    </value>
    <value>
       <code>bf</code>
        <country>Bahamas</country>
    </value>
    <value>
       <code>bg</code>
        <country>Bangladesh</country>
    </value>
    <value>
       <code>bh</code>
        <country>Belize</country>
    </value>
    <value>
       <code>bi</code>
        <country>British Indian Ocean Territory</country>
    </value>
    <value>
       <code>bl</code>
        <country>Brazil</country>
    </value>
    <value>
       <code>bm</code>
        <country>Bermuda Islands</country>
    </value>
    <value>
       <code>bn</code>
        <country>Bosnia and Herzegovina</country>
    </value>
    <value>
       <code>bo</code>
        <country>Bolivia</country>
    </value>
    <value>
       <code>bp</code>
        <country>Solomon Islands</country>
    </value>
    <value>
       <code>br</code>
        <country>Burma</country>
    </value>
    <value>
       <code>bs</code>
        <country>Botswana</country>
    </value>
    <value>
       <code>bt</code>
        <country>Bhutan</country>
    </value>
    <value>
       <code>bu</code>
        <country>Bulgaria</country>
    </value>
    <value>
       <code>bv</code>
        <country>Bouvet Island</country>
    </value>
    <value>
       <code>bw</code>
        <country>Belarus</country>
    </value>
    <value>
       <code>-bwr</code>
        <country>Byelorussian S.S.R.</country>
    </value>
    <value>
       <code>bx</code>
        <country>Brunei</country>
    </value>
    <value>
       <code>ca</code>
        <country>Caribbean Netherlands</country>
    </value>
    <value>
       <code>cau</code>
        <country>California</country>
    </value>
    <value>
       <code>cb</code>
        <country>Cambodia</country>
    </value>
    <value>
       <code>cc</code>
        <country>China</country>
    </value>
    <value>
       <code>cd</code>
        <country>Chad</country>
    </value>
    <value>
       <code>ce</code>
        <country>Sri Lanka</country>
    </value>
    <value>
       <code>cf</code>
        <country>Congo (Brazzaville)</country>
    </value>
    <value>
       <code>cg</code>
        <country>Congo (Democratic Republic)</country>
    </value>
    <value>
       <code>ch</code>
        <country>China (Republic : 1949- )</country>
    </value>
    <value>
       <code>ci</code>
        <country>Croatia</country>
    </value>
    <value>
       <code>cj</code>
        <country>Cayman Islands</country>
    </value>
    <value>
       <code>ck</code>
        <country>Colombia</country>
    </value>
    <value>
       <code>cl</code>
        <country>Chile</country>
    </value>
    <value>
       <code>cm</code>
        <country>Cameroon</country>
    </value>
    <value>
       <code>-cn</code>
        <country>Canada</country>
    </value>
    <value>
       <code>co</code>
        <country>Curaçao</country>
    </value>
    <value>
       <code>cou</code>
        <country>Colorado</country>
    </value>
    <value>
       <code>-cp</code>
        <country>Canton and Enderbury Islands</country>
    </value>
    <value>
       <code>cq</code>
        <country>Comoros</country>
    </value>
    <value>
       <code>cr</code>
        <country>Costa Rica</country>
    </value>
    <value>
       <code>-cs</code>
        <country>Czechoslovakia</country>
    </value>
    <value>
       <code>ctu</code>
        <country>Connecticut</country>
    </value>
    <value>
       <code>cu</code>
        <country>Cuba</country>
    </value>
    <value>
       <code>cv</code>
        <country>Cabo Verde</country>
    </value>
    <value>
       <code>cw</code>
        <country>Cook Islands</country>
    </value>
    <value>
       <code>cx</code>
        <country>Central African Republic</country>
    </value>
    <value>
       <code>cy</code>
        <country>Cyprus</country>
    </value>
    <value>
       <code>-cz</code>
        <country>Canal Zone</country>
    </value>
    <value>
       <code>dcu</code>
        <country>District of Columbia</country>
    </value>
    <value>
       <code>deu</code>
        <country>Delaware</country>
    </value>
    <value>
       <code>dk</code>
        <country>Denmark</country>
    </value>
    <value>
       <code>dm</code>
        <country>Benin</country>
    </value>
    <value>
       <code>dq</code>
        <country>Dominica</country>
    </value>
    <value>
       <code>dr</code>
        <country>Dominican Republic</country>
    </value>
    <value>
       <code>ea</code>
        <country>Eritrea</country>
    </value>
    <value>
       <code>ec</code>
        <country>Ecuador</country>
    </value>
    <value>
       <code>eg</code>
        <country>Equatorial Guinea</country>
    </value>
    <value>
       <code>em</code>
        <country>Timor-Leste</country>
    </value>
    <value>
       <code>enk</code>
        <country>England</country>
    </value>
    <value>
       <code>er</code>
        <country>Estonia</country>
    </value>
    <value>
       <code>-err</code>
        <country>Estonia</country>
    </value>
    <value>
       <code>es</code>
        <country>El Salvador</country>
    </value>
    <value>
       <code>et</code>
        <country>Ethiopia</country>
    </value>
    <value>
       <code>fa</code>
        <country>Faroe Islands</country>
    </value>
    <value>
       <code>fg</code>
        <country>French Guiana</country>
    </value>
    <value>
       <code>fi</code>
        <country>Finland</country>
    </value>
    <value>
       <code>fj</code>
        <country>Fiji</country>
    </value>
    <value>
       <code>fk</code>
        <country>Falkland Islands</country>
    </value>
    <value>
       <code>flu</code>
        <country>Florida</country>
    </value>
    <value>
       <code>fm</code>
        <country>Micronesia (Federated States)</country>
    </value>
    <value>
       <code>fp</code>
        <country>French Polynesia</country>
    </value>
    <value>
       <code>fr</code>
        <country>France</country>
    </value>
    <value>
       <code>fs</code>
        <country>Terres australes et antarctiques françaises</country>
    </value>
    <value>
       <code>ft</code>
        <country>Djibouti</country>
    </value>
    <value>
       <code>gau</code>
        <country>Georgia</country>
    </value>
    <value>
       <code>gb</code>
        <country>Kiribati</country>
    </value>
    <value>
       <code>gd</code>
        <country>Grenada</country>
    </value>
    <value>
       <code>-ge</code>
        <country>Germany (East)</country>
    </value>
    <value>
       <code>gg</code>
        <country>Guernsey</country>
    </value>
    <value>
       <code>gh</code>
        <country>Ghana</country>
    </value>
    <value>
       <code>gi</code>
        <country>Gibraltar</country>
    </value>
    <value>
       <code>gl</code>
        <country>Greenland</country>
    </value>
    <value>
       <code>gm</code>
        <country>Gambia</country>
