=== CarlosMartinez-USDA/NAL-MARCXML2MODS3-7/commons/xml/nalSubjCat.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"
  targetNamespace="http://nal-subject-category-codes"
  xmlns:nalsubcat="http://nal-subject-category-codes">
  <xs:element name="agricola">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="nalsubcat:subject"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="subject">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="nalsubcat:code"/>
        <xs:element ref="nalsubcat:category"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="code" type="xs:NCName"/>
  <xs:element name="category" type="xs:string"/>
</xs:schema>

=== CarlosMartinez-USDA/NAL-MARCXML2MODS3-7/commons/xml/nalSubjCat.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS FILE IS USED TO CONVERT AGRICOLA SUBJECT CATEGORY CODES TO ITS REPSECTIVE SUBJECT TERM -->
<agricola
	xmlns="http://nal-subject-category-codes" 
	xmlns:nalsubcat="http://nal-subject-category-codes"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://nal-subject-category-codes nalSubjCat.xsd">
	<subject>
		<code>A000</code>
		<category>Agriculture (General)</category>
	</subject>
	<subject>
		<code>A500</code>
		<category>Agricultural Research and Methodology</category>
	</subject>
	<subject>
		<code>B100</code>
		<category>Geography</category>
	</subject>
	<subject>
		<code>B200</code>
		<category>Meteorology and Climatology</category>
	</subject>
	<subject>
		<code>B500</code>
		<category>Agricultural History and Biography</category>
	</subject>
	<subject>
		<code>C100</code>
		<category>Agricultural Education and Training (Not Extension)</category>
	</subject>
	<subject>
		<code>C200</code>
		<category>Extension and Advisory Work (Non U.S.)</category>
	</subject>
	<subject>
		<code>C210</code>
		<category>U.S. Extension Services</category>
	</subject>
	<subject>
		<code>D100</code>
		<category>Administration of Agricultural Agencies and Organizations</category>
	</subject>
	<subject>
		<code>D500</code>
		<category>Laws and Regulations</category>
	</subject>
	<subject>
		<code>E100</code>
		<category>Agricultural Economics (General)</category>
	</subject>
	<subject>
		<code>E110</code>
		<category>Land Development, Land Reform and Utilization (Macroeconomics)</category>
	</subject>
	<subject>
		<code>E130</code>
		<category>Agricultural Production (Macroeconomics)</category>
	</subject>
	<subject>
		<code>E200</code>
		<category>Farm Organization and Management (Microeconomics)</category>
	</subject>
	<subject>
		<code>E300</code>
		<category>International Agricultural Development Aid Programs</category>
	</subject>
	<subject>
		<code>E310</code>
		<category>U.S. Food and Nutrition Programs</category>
	</subject>
	<subject>
		<code>E400</code>
		<category>Cooperatives</category>
	</subject>
	<subject>
		<code>E500</code>
		<category>Rural Sociology</category>
	</subject>
	<subject>
		<code>E550</code>
		<category>Rural Development</category>
	</subject>
	<subject>
		<code>E560</code>
		<category>Rural Community Public Services</category>
	</subject>
	<subject>
		<code>E700</code>
		<category>Distribution and Marketing of Agricultural Products</category>
	</subject>
	<subject>
		<code>E710</code>
		<category>Grading, Standards, Labeling</category>
	</subject>
	<subject>
		<code>E720</code>
		<category>Consumer Economics</category>
	</subject>
	<subject>
		<code>F000</code>
		<category>Plant Science (General)</category>
	</subject>
	<subject>
		<code>F100</code>
		<category>Plant Production (General)</category>
	</subject>
	<subject>
		<code>F110</code>
		<category>Plant Production (Horticultural Crops)</category>
	</subject>
	<subject>
		<code>F120</code>
		<category>Plant Production (Field Crops)</category>
	</subject>
	<subject>
		<code>F130</code>
		<category>Plant Production (Range and Pasture Crops)</category>
	</subject>
	<subject>
		<code>F140</code>
		<category>Plant Production (Miscellaneous Crops)</category>
	</subject>
	<subject>
		<code>F200</code>
		<category>Plant Breeding and Genetics</category>
	</subject>
	<subject>
		<code>F300</code>
		<category>Plant Ecology</category>
	</subject>
	<subject>
		<code>F400</code>
		<category>Plant Structure</category>
	</subject>
	<subject>
		<code>F500</code>
		<category>Plant Nutrition</category>
	</subject>
	<subject>
		<code>F600</code>
		<category>Plant Physiology and Biochemistry</category>
	</subject>
	<subject>
		<code>F700</code>
		<category>Plant Taxonomy, Collection, and Geography</category>
	</subject>
	<subject>
		<code>F800</code>
		<category>Protection of Plants</category>
	</subject>
	<subject>
		<code>F820</code>
		<category>Pests of Plants (Animals)</category>
	</subject>
	<subject>
		<code>F821</code>
		<category>Pests of Plants (Insects and Other Arthropods)</category>
	</subject>
	<subject>
		<code>F822</code>
		<category>Pests of Plants (Nematodes)</category>
	</subject>
	<subject>
		<code>F830</code>
		<category>Plant Diseases (General)</category>
	</subject>
	<subject>
		<code>F831</code>
		<category>Plant Diseases (Fungi)</category>
	</subject>
	<subject>
		<code>F832</code>
		<category>Plant Diseases (Bacterial)</category>
	</subject>
	<subject>
		<code>F833</code>
		<category>Plant Diseases (Viral)</category>
	</subject>
	<subject>
		<code>F840</code>
		<category>Plant Diseases (Physiological)</category>
	</subject>
	<subject>
		<code>F841</code>
		<category>Miscellaneous Plant Disorders and Injuries</category>
	</subject>
	<subject>
		<code>F850</code>
		<category>Protection of Plant Products (General)</category>
	</subject>
	<subject>
		<code>F851</code>
		<category>Protection of Plant Products (Insects and Other Arthropods)</category>
	</subject>
	<subject>
		<code>F900</code>
		<category>Weeds and Other Noxious Plants</category>
	</subject>
	<subject>
		<code>H000</code>
		<category>Pesticides (General)</category>
	</subject>
	<subject>
		<code>J000</code>
		<category>Soil Sciences</category>
	</subject>
	<subject>
		<code>J100</code>
		<category>Soil Biology</category>
	</subject>
	<subject>
		<code>J200</code>
		<category>Soil Chemistry and Physics</category>
	</subject>
	<subject>
		<code>J300</code>
		<category>Soil Classification and Genesis</category>
	</subject>
	<subject>
		<code>J400</code>
		<category>Soil Surveying and Mapping</category>
	</subject>
	<subject>
		<code>J500</code>
		<category>Soil Fertility, Fertilizers, and Manures</category>
	</subject>
	<subject>
		<code>J600</code>
		<category>Soil Resources and Management</category>
	</subject>
	<subject>
		<code>J700</code>
		<category>Soil Cultivation and Cropping Systems</category>
	</subject>
	<subject>
		<code>J710</code>
		<category>Alternative Farming Systems</category>
	</subject>
	<subject>
		<code>J800</code>
		<category>Soil Conservation</category>
	</subject>
	<subject>
		<code>K000</code>
		<category>Forestry</category>
	</subject>
	<subject>
		<code>K001</code>
		<category>Forestry Related</category>
	</subject>
	<subject>
		<code>K100</code>
		<category>Forestry Production (General)</category>
	</subject>
	<subject>
		<code>K110</code>
		<category>Forestry Production (Natural Regeneration)</category>
	</subject>
	<subject>
		<code>K120</code>
		<category>Forestry Production (Artificial Regeneration)</category>
	</subject>
	<subject>
		<code>K130</code>
		<category>Forestry Production (Harvesting and Engineering)</category>
	</subject>
	<subject>
		<code>K200</code>
		<category>Forest Management</category>
	</subject>
	<subject>
		<code>K250</code>
		<category>Forest Mensuration and Description</category>
	</subject>
	<subject>
		<code>K500</code>
		<category>Forest Products (General)</category>
	</subject>
	<subject>
		<code>K510</code>
		<category>Forest Products (Wood)</category>
	</subject>
	<subject>
		<code>K520</code>
		<category>Forest Products (Composite and Reconstituted Wood)</category>
	</subject>
	<subject>
		<code>K530</code>
		<category>Forest Products (Pulp and Paper)</category>
	</subject>
	<subject>
		<code>K540</code>
		<category>Forest Products (Chemicals)</category>
	</subject>
	<subject>
		<code>K590</code>
		<category>Forest Products (Miscellaneous)</category>
	</subject>
	<subject>
		<code>K800</code>
		<category>Forest Injuries and Protection</category>
	</subject>
	<subject>
		<code>K810</code>
		<category>Forest Fire Management</category>
	</subject>
	<subject>
		<code>L000</code>
		<category>Animal Science</category>
	</subject>
	<subject>
		<code>L001</code>
		<category>Entomology Related</category>
	</subject>
	<subject>
		<code>L002</code>
		<category>Apiculture Related</category>
	</subject>
	<subject>
		<code>L003</code>
		<category>Sericulture Related</category>
	</subject>
	<subject>
		<code>L100</code>
		<category>Animal Production</category>
	</subject>
	<subject>
		<code>L110</code>
		<category>Laboratory and Experimental Animals</category>
	</subject>
	<subject>
		<code>L200</code>
		<category>Animal Breeding and Genetics</category>
	</subject>
	<subject>
		<code>L210</code>
		<category>Animal Reproduction</category>
	</subject>
	<subject>
		<code>L300</code>
		<category>Animal Ecology and Behavior</category>
	</subject>
	<subject>
		<code>L400</code>
		<category>Animal Structure</category>
	</subject>
	<subject>
		<code>L500</code>
		<category>Animal Nutrition</category>
	</subject>
	<subject>
		<code>L600</code>
		<category>Animal Physiology and Biochemistry</category>
	</subject>
	<subject>
		<code>L700</code>
		<category>Animal Taxonomy and Geography</category>
	</subject>
	<subject>
		<code>L800</code>
		<category>Veterinary Science</category>
	</subject>
	<subject>
		<code>L810</code>
		<category>Veterinary Pharmacology, Toxicology, and Immunology</category>
	</subject>
	<subject>
		<code>L820</code>
		<category>Pests of Animals (General)</category>
	</subject>
	<subject>
		<code>L821</code>
		<category>Pests of Animals (Insects and Other Arthropods)</category>
	</subject>
	<subject>
		<code>L822</code>
		<category>Pests of Animals (Helminths)</category>
	</subject>
	<subject>
		<code>L823</code>
		<category>Pests of Animals (Protozoa)</category>
	</subject>
	<subject>
		<code>L830</code>
		<category>Animal Diseases (General)</category>
	</subject>
	<subject>
		<code>L831</code>
		<category>Animal Diseases (Fungal)</category>
	</subject>
	<subject>
		<code>L832</code>
		<category>Animal Diseases (Bacterial)</category>
	</subject>
	<subject>
		<code>L833</code>
		<category>Animal Diseases (Viral)</category>
	</subject>
	<subject>
		<code>L840</code>
		<category>Animal Diseases (Physiological)</category>
	</subject>
	<subject>
		<code>L841</code>
		<category>Animal Disorders and Injuries</category>
	</subject>
	<subject>
